# Numpy 

In [1]:
import numpy as np

In [9]:
list1= list(range(0,100))
a= np.array(list1)
print(a, type(a))
print(a[10])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] <class 'numpy.ndarray'>
10


 ## Memory comparison between list and np.array

In [12]:
import sys

l = range(1000)
print("List size: ",sys.getsizeof(5)*len(l))

array= np.arange(1000)
print("Array size: ",array.size*array.itemsize)

List size:  28000
Array size:  8000


## speed comparison between list and array

In [15]:
import time

size=100000

l1=range(size)
l2=range(size)
start=time.time()  #marging 2 lists
res=[(x+y) for x,y in zip(l1,l2)]
print("List Time: ",(time.time()-start)*1000)


a1=np.arange(size)
a2=np.arange(size)
start=time.time()
res=a1+a2          #marging 2 arrays
print("Array Time: ",(time.time()-start)*1000)



List Time:  28.85580062866211
Array Time:  3.3621788024902344


## Different dimentional arrays

In [17]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(a.ndim,b.ndim)


1 2


In [23]:
print(a.itemsize)
print(b.dtype)

8
int64


In [22]:
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [25]:
b.shape

(2, 5)

In [26]:
zero= np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
ones= np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
b= np.linspace(1,5,10)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [38]:
c=np.array([[1,2],[3,4],[5,6]])
c.shape

(3, 2)

## changing the shape of an array

In [42]:
d=c.reshape(2,3)
e=c.reshape(6,1)
print(d)
print(e)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
print(c.ravel())   # making 1 dimentional array

[1 2 3 4 5 6]


## some useful mathamatical operations in np

In [45]:
c.min()

1

In [46]:
c.max()

6

In [47]:
c.sum()

21

In [48]:
 c.sum(axis=0)  # colum wise sum

array([ 9, 12])

In [49]:
c.sum(axis=1)   # row wide sum

array([ 3,  7, 11])

In [52]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,7],[8,9]])
print(a)
print(b)


[[1 2]
 [4 5]]
[[6 7]
 [8 9]]
[[ 7  9]
 [12 14]]


In [53]:
print(a+b)

[[ 7  9]
 [12 14]]


In [54]:
print(a*b)

[[ 6 14]
 [32 45]]


In [55]:
print(a/b)

[[0.16666667 0.28571429]
 [0.5        0.55555556]]


In [56]:
a.dot(b)  # Matrix product

array([[22, 25],
       [64, 73]])

## slicing and stacking 

In [69]:
a=np.array([[1,2,3],[4,5,6],[7,9,10]])
print(a)
a[1,2]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  9 10]]


6

In [71]:
a[0:3,2]

array([ 3,  6, 10])

In [72]:
a[-1,0:2]

array([7, 9])

In [74]:
a[:,1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 9, 10]])

## itaration through a array

In [75]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[ 7  9 10]


In [77]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
9
10


## Stacking Arrays

In [81]:
a=np.arange(0,6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [82]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [83]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## Spliting Arrays

In [94]:
a= np.arange(0,40).reshape(4,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [96]:
result=np.hsplit(a,5)
for i in result:
    print(i)
    print("size is:",len(i))

[[ 0  1]
 [10 11]
 [20 21]
 [30 31]]
size is: 4
[[ 2  3]
 [12 13]
 [22 23]
 [32 33]]
size is: 4
[[ 4  5]
 [14 15]
 [24 25]
 [34 35]]
size is: 4
[[ 6  7]
 [16 17]
 [26 27]
 [36 37]]
size is: 4
[[ 8  9]
 [18 19]
 [28 29]
 [38 39]]
size is: 4


In [97]:
result=np.vsplit(a,2)
for i in result:
    print(i)
    print("size is:",len(i))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
size is: 2
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
size is: 2


In [100]:
a= np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Boolian Array

In [101]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [102]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [106]:
a[b]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])