In [3]:
import pandas as pd
import numpy as np 
from sklearn import linear_model

In [7]:
# reading the data from the csv file
df= pd.read_csv("homeprice.csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
# filtering the data by removing the Null values with proper substitute
import math
median_bedroom= math.floor(df.bedrooms.median())
median_bedroom

4

In [10]:
# making 
df.bedrooms= df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
# train the model
x=df[['area','bedrooms','age']]
y=df.price
model= linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [14]:
model.score(x,y)

0.9550196399325819

In [16]:
model.predict([[5000,3.0,2]])

array([845338.41599263])

In [17]:
import pickle

In [19]:
# saving the trained model in a file using pickle
with open('model_pickle','wb')as f:
    pickle.dump(model,f)

In [22]:
with open('model_pickle','rb') as f:
    pkl_model = pickle.load(f)

In [23]:
pkl_model.predict([[5000,3.0,2]])

array([845338.41599263])

In [27]:
# saving the trained model in a file using joblib
import joblib
joblib.dump(model,'joblib_model.pkl')

['joblib_model.pkl']

In [29]:
jlib_model= joblib.load('joblib_model.pkl')

In [30]:
jlib_model.predict([[5000,3.0,2]])

array([845338.41599263])